# Generated by Django 4.0.1 on 2022-03-01 12:41

import Ihute_on_off_street.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('transaction_status', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, default=Ihute_on_off_street.utils.create_new_ref_number, editable=False, max_length=10, unique=True)),
                ('sub_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15, null=True)),
                ('tin_number', models.CharField(max_length=64, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('make_year', models.CharField(max_length=10, null=True)),
                ('vehicule_model', models.CharField(max_length=64, null=True)),
                ('parking_wallet', models.IntegerField(default=0)),
                ('sub_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subscriber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
