# Generated by Django 4.0.1 on 2022-03-03 14:49

import Ihute_on_off_street.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ihute_on_off_street', '0002_alter_subscriber_sub_id_alter_transaction_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='sub_id',
            field=models.OneToOneField(blank=True, default=Ihute_on_off_street.utils.create_new_ref_number, editable=False, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
