# Generated by Django 4.0.1 on 2022-03-03 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ihute_on_off_street', '0003_alter_subscriber_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='sub_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
