# Generated by Django 4.0.1 on 2022-03-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihute_on_off_street', '0005_subscriber_vin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Transaction_type',
            field=models.CharField(choices=[('E_Parking', 'Pay_parking'), ('E_Insurance', 'Buy_insurance'), ('Mechanical_serv', 'Book_mechanic')], default=1, max_length=32),
            preserve_default=False,
        ),
    ]
