# Generated by Django 4.0.1 on 2022-03-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihute_on_off_street', '0006_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_type',
            field=models.CharField(choices=[('E_Parking', 'Pay_parking'), ('E_Insurance', 'Buy_insurance'), ('Mechanical_serv', 'Book_mechanic'), ('Chauffeur_4hire', 'Chauffeur_4hire')], max_length=32),
        ),
    ]
