# Generated by Django 4.0.1 on 2022-03-21 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ihute_on_off_street', '0007_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('E_Parking', 'Pay_receipt'), ('E_Insurance', 'Pay_receipt'), ('Mechanical_serv', 'Pay_receipt'), ('Chauffeur_4hire', 'Pay_receipt')], max_length=32)),
                ('sub_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
