# Generated by Django 4.0.1 on 2022-03-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihute_on_off_street', '0008_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='service_type',
            field=models.CharField(choices=[('E_Parking', 'E_Parking'), ('E_Insurance', 'E_Insurance'), ('Mechanical_serv', 'Mechanical_serv'), ('Chauffeur_4hire', 'Chauffeur_4hire')], max_length=32),
        ),
    ]
