# Generated by Django 4.0.1 on 2022-03-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihute_on_off_street', '0010_rename_sub_id_provider_provider_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='provider_id',
            new_name='provider',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(choices=[('E_Parking', 'E_Parking'), ('E_Insurance', 'E_Insurance'), ('Mechanical_serv', 'Mechanical_serv'), ('Chauffeur_4hire', 'Chauffeur_4hire')], max_length=50),
        ),
    ]
