# Generated by Django 4.0.1 on 2022-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihute_on_off_street', '0012_rename_vin_number_subscriber_chassis_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposed_insucovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Third_party_liabilityGuarantee', models.BooleanField(default=False)),
                ('window_breaking', models.BooleanField(default=False)),
                ('Recoure', models.BooleanField(default=False)),
                ('material_damaged', models.BooleanField(default=False)),
                ('Theft_Covers', models.CharField(max_length=20)),
                ('Fire_Covers', models.BooleanField(default=False)),
                ('Third_party_plus', models.BooleanField(default=False)),
                ('Without_deductible', models.BooleanField(default=False)),
                ('Only_Localy_coverd', models.BooleanField(default=False)),
                ('Towing_system', models.BooleanField(default=False)),
                ('accident_hist4thelast2years', models.CharField(max_length=20)),
                ('was_your_previous_policy_canceled', models.BooleanField(default=False)),
            ],
        ),
    ]
