# Generated by Django 4.0.1 on 2022-04-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihute_on_off_street', '0014_proposed_insucovers_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposed_insucovers',
            name='Theft_Covers',
            field=models.BooleanField(default=False),
        ),
    ]
